namespace Game.Achievements;

public enum AchievementType
{
	None = 0,
	ShrugItOff = 1,
	Purity = 2,
	ComeAtMe = 3,
	ThePact = 4,
	Adrenaline = 5,
	Powerful = 6,
	Jaxxed = 7,
	Impervious = 8,
	Barricaded = 9,
	Catalyst = 10,
	Plague = 11,
	Ninja = 12,
	Infinity = 13,
	Focused = 14,
	Neon = 15,
	YouAreNothing = 16,
	Minimalist = 17,
	OohDonut = 18,
	Perfect = 19,
	WhoNeedsRelics = 20,
	SpeedClimber = 21,
	CommonSense = 22,
	TheTransient = 24,
	TheGuardian = 25,
	TheGhost = 26,
	TheBoss = 27,
	TheAutomaton = 28,
	TheCollector = 29,
	TheChampion = 30,
	TheCrow = 31,
	TheShapes = 32,
	TheTimeEater = 33,
	Ruby = 34,
	Emerald = 35,
	Sapphire = 36,
	Amethyst = 37,
	RubyPlus = 38,
	EmeraldPlus = 39,
	SapphirePlus = 40,
	AmethystPlus = 41,
	TheEnd = 42,
	EternalOne = 43
}
